name:                mambda
version:             0.1.0.0
github:              "batkot/mambda"
license:             WTFPL
author:              "Tomasz Batko"
maintainer:          "batkot@protonmail.com"
copyright:           "Tomasz Batko"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            CLI Snake 
category:            games

description:         Please see the README on GitHub at <https://github.com/batkot/mambda#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  mambda:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mambda
    - ansi-terminal >= 0.9 && < 1
    - async >= 2.2 && < 3
    - optparse-applicative >= 0.14 && < 1
    - transformers >= 0.5 && < 1

tests:
  mambda-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mambda
    - tasty >= 1.2 && < 2.0
    - tasty-discover >= 4.2 && < 5
    - tasty-quickcheck >= 0.10 && < 1
    - QuickCheck >= 2.13 && < 3
