name:                mambda-cli
version:             0.1.0.0
github:              "batkot/mambda"
license:             MIT
author:              "Tomasz Batko"
maintainer:          "batkot@protonmail.com"
copyright:           "2026 Tomasz Batko"

language: GHC2024

default-extensions:
- NoFieldSelectors
- NoImplicitPrelude
- OverloadedStrings
- OverloadedLabels
- DeriveAnyClass
- GADTs

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/batkot/mambda#readme>

dependencies:
- aztecs
- base >= 4.7 && < 5
- linear
- vector

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  mambda:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brick
    - bytestring
    - containers
    - file-embed
    - generic-optics
    - mambda-cli
    - optics-core
    - text
    - vector
    - vty

tests:
  unit:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mambda-cli
    - QuickCheck
    - HUnit
    - tasty
    - tasty-discover
    - tasty-quickcheck
    - tasty-hunit